version: "3.8"
services:
  postgres:
    container_name: finance_ai
    image: postgres:16
    ports:
      - "5000:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - finance-ai-vol:/var/lib/postgresql/data

volumes:
  finance-ai-vol:
